# Generated by Django 2.2.6 on 2019-12-14 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Pasar',
                'db_table': 'Tb_Pasar',
            },
        ),
        migrations.CreateModel(
            name='Sembako',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('satuan', models.CharField(choices=[('kg', 'kg'), ('Bungkus', 'Bungkus'), ('Liter', 'Liter')], default='kg', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Sembako',
                'db_table': 'Tb_Sembako',
            },
        ),
        migrations.CreateModel(
            name='PetugasPasar',
            fields=[
                ('akun', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nama', models.CharField(max_length=100)),
                ('jenis_kelamin', models.CharField(choices=[('LK', 'Laki - Laki'), ('PR', 'Wanita')], default='LK', max_length=20)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('Tanggal_lahir', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('No_hp', models.CharField(max_length=100)),
                ('pasar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sishasembapo.Pasar')),
            ],
            options={
                'verbose_name_plural': 'Petugas Pasar',
                'db_table': 'tb_Petugas_Pasar',
            },
        ),
        migrations.CreateModel(
            name='Harga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('nominal', models.IntegerField()),
                ('validasi', models.BooleanField(default=False)),
                ('nama_pasar', models.ForeignKey(db_column='nama_pasar', on_delete=django.db.models.deletion.CASCADE, to='sishasembapo.Pasar')),
                ('nama_sembako', models.ForeignKey(db_column='nama_barang', on_delete=django.db.models.deletion.CASCADE, to='sishasembapo.Sembako')),
            ],
            options={
                'verbose_name_plural': 'Harga',
                'db_table': 'Tb_Harga',
            },
        ),
    ]
