# Generated by Django 2.2.6 on 2019-12-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sishasembapo', '0003_auto_20191214_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petugaspasar',
            name='Tanggal_lahir',
            field=models.DateField(),
        ),
    ]
