# Generated by Django 3.0.3 on 2020-02-11 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sishasembapo', '0004_auto_20191219_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Satuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satuan', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Satuan',
                'db_table': 'Tb_Satuan',
            },
        ),
        migrations.AlterField(
            model_name='sembako',
            name='satuan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sishasembapo.Satuan', verbose_name='Satuan'),
        ),
    ]
