# Generated by Django 3.0.3 on 2020-03-05 07:28

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('sishasembapo', '0005_auto_20200211_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasar',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63, null=True),
        ),
    ]
