# Generated by Django 3.0.3 on 2020-03-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sishasembapo', '0007_auto_20200305_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasar',
            name='kecamatan',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pasar',
            name='kelurahan',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pasar',
            name='notlp',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
