# Generated by Django 3.0.3 on 2020-04-10 03:18

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('sishasembapo', '0008_auto_20200310_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasar',
            name='lokasi',
            field=location_field.models.plain.PlainLocationField(help_text='(Latitude,Longtitude)', max_length=63, null=True),
        ),
    ]
