# Generated by Django 3.0.3 on 2020-05-07 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sishasembapo', '0010_auto_20200507_1235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Satuan',
        ),
    ]
