# Generated by Django 3.0.3 on 2020-05-07 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sishasembapo', '0012_satuan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Satuan',
        ),
    ]
