# Generated by Django 3.0.3 on 2020-05-25 03:48

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('sishasembapo', '0014_auto_20200525_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasar',
            name='lokasi',
            field=mapbox_location_field.models.LocationField(help_text='(Latitude,Longtitude)', map_attrs={'center': [0, 0], 'marker_color': 'blue'}),
        ),
    ]
