# Generated by Django 3.0.3 on 2020-05-25 03:53

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('sishasembapo', '0015_auto_20200525_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasar',
            name='lokasi',
            field=mapbox_location_field.models.LocationField(help_text='(Longtitude, Latitude)', map_attrs={'center': [111.999458, -7.817179], 'marker_color': 'blue', 'placeholder': 'Silahkan Pilih lokasi'}),
        ),
    ]
