# Generated by Django 3.0.3 on 2020-06-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sishasembapo', '0017_auto_20200615_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harga',
            name='validasi',
            field=models.CharField(choices=[('1', 'Disetujui'), ('2', 'Ditolak'), ('3', 'Belum Diperiksa')], default='3', max_length=2),
        ),
    ]
